import { useState } from 'react';
import { PRESET_AREAS, PRESET_EVENTS, presetById, expandAbbreviations } from '../data/presets';
import { IntakePanel } from './IntakePanel';
import type { IntakeState } from '../state';

interface Props {
  intake: IntakeState;
  setIntake: (i: IntakeState) => void;
  onContinue: (presetId: string | null) => void;
}

/**
 * Step 1 — pick what the policy is for and hand over all information in one place.
 * Previous ELSA events (from approved policies,
 * generated by scripts/build-presets.py) are chosen via area filter + dropdown.
 * The A/B/C intake opens inline inside the chosen box — no separate step.
 */
export function StepChooseEvent({ intake, setIntake, onContinue }: Props) {
  const [choice, setChoice] = useState<'none' | 'new' | 'preset'>('none');
  const [area, setArea] = useState('');
  const [presetId, setPresetId] = useState('');
  const preset = presetById(presetId || null);

  const filtered = PRESET_EVENTS.filter((p) => !area || p.area === area);
  const hasInput = intake.files.length > 0 || intake.pasted.trim() || intake.manual.trim();
  const canContinue = choice === 'preset' ? !!preset : choice === 'new' ? !!hasInput : false;

  return (
    <section className="step">
      <h2>Step 1 · What are you creating a privacy policy for?</h2>

      <h3 className="choose-heading">Start from a previous ELSA event</h3>
      <p className="hint">Its most recent <b>approved</b> privacy policy becomes the foundation: data subjects,
        categories, purposes, legal bases and recipients are pre-filled and marked orange for review.</p>
      <div className="preset-pickers">
        <label>ELSA area
          <select value={area} onChange={(e) => { setArea(e.target.value); setPresetId(''); }}>
            <option value="">All areas ({PRESET_EVENTS.length} events)</option>
            {PRESET_AREAS.map((a) => (
              <option key={a} value={a}>{a} ({PRESET_EVENTS.filter((p) => p.area === a).length})</option>
            ))}
          </select>
        </label>
        <label>Previous event
          <select
            value={presetId}
            onChange={(e) => { setPresetId(e.target.value); setChoice(e.target.value ? 'preset' : 'none'); }}
          >
            <option value="">— choose an event —</option>
            {filtered.map((p) => {
              const full = expandAbbreviations(p.name);
              return (
                <option key={p.id} value={p.id}>
                  {p.name}{full ? ` — ${full}` : ''}{p.lastUpdated ? ` (${p.lastUpdated})` : ''}
                </option>
              );
            })}
          </select>
        </label>
      </div>

      {choice === 'preset' && preset && (
        <div className="event-card chosen preset-box">
          <span className="event-name">{preset.name}{expandAbbreviations(preset.name) ? ` — ${expandAbbreviations(preset.name)}` : ''}</span>
          <span className="hint">{preset.area} · based on: {preset.sourceFile}{preset.lastUpdated ? ` · last updated ${preset.lastUpdated}` : ''}</span>
          <span className="event-source">
            Pre-filled from the approved policy: {preset.categories.length + preset.customCategories.length} data
            categories, {preset.purposes.length} purposes with legal bases, {preset.recipients.length} recipients
            {preset.transfersOutsideEEA ? ', transfers outside the EEA' : ''}. You review and adapt everything in the
            next step — points that typically change are flagged right next to the relevant question.
          </span>
          <div className="inline-intake">
            <p className="lead">Add anything you already have for this edition (all optional):</p>
            <IntakePanel intake={intake} setIntake={setIntake} mode="preset" presetName={preset.name} />
            {!hasInput && (
              <button className="skip-btn" onClick={() => onContinue(presetId)}>
                Skip A/B/C — straight to Complete &amp; check →
              </button>
            )}
          </div>
        </div>
      )}

      <h3 className="choose-heading new-heading">…or create a new one</h3>
      <button
        className={`event-card new ${choice === 'new' ? 'chosen' : ''}`}
        onClick={() => { setChoice('new'); setPresetId(''); }}
      >
        <span className="event-name">＋ New event — or a previous event that is not listed above</span>
        <span className="hint">For an event or activity without a listed privacy policy. Describe it below — or upload
          the previous privacy policy of an unlisted event under A — and the tool pre-fills whatever it recognises; you
          review everything afterwards.</span>
      </button>

      {choice === 'new' && (
        <div className="event-card chosen preset-box new-box">
          <span className="event-name">New event</span>
          <div className="inline-intake">
            <p className="lead">Tell the tool everything about your event — it scans it on your device only:</p>
            <IntakePanel intake={intake} setIntake={setIntake} mode="new" />
          </div>
        </div>
      )}

      <div className="actions">
        <button
          className="primary" disabled={!canContinue}
          onClick={() => onContinue(choice === 'preset' ? presetId : null)}
        >
          {choice === 'preset' && preset ? `Continue with ${preset.name} →` : 'Scan & continue →'}
        </button>
        {choice === 'new' && !hasInput && <span className="hint">Add at least one document or some text to continue.</span>}
        {choice === 'none' && <span className="hint">Pick a previous event or choose “New event” to begin.</span>}
      </div>
    </section>
  );
}
